name: Linux-XFCE-RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
    - name: Install XFCE Desktop Environment and XRDP
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp
        sudo systemctl enable xrdp

    - name: Configure XRDP to use XFCE
      run: |
        echo "startxfce4" | sudo tee /etc/xrdp/startwm.sh
        sudo systemctl restart xrdp

    - name: Create RDP User with Secure Password
      run: |
        password=$(openssl rand -base64 12)
        sudo useradd -m -s /bin/bash AiraaCheisyaa
        echo "AiraaCheisyaa:$password" | sudo chpasswd
        sudo adduser AiraaCheisyaa sudo
        sudo adduser AiraaCheisyaa xrdp
        echo "RDP_CREDS=User: AiraaCheisyaa | Password: $password" >> $GITHUB_ENV
        echo "RDP_PASSWORD=$password" >> $GITHUB_ENV

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Establish Tailscale Connection
      run: |
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID
        ts_ip=$(sudo tailscale ip -4)
        echo "TAILSCALE_IP=$ts_ip" >> $GITHUB_ENV

    - name: Verify RDP Accessibility
      run: |
        echo "Tailscale IP: $TAILSCALE_IP"
        # Verifikasi bahwa port RDP (3389) dapat dijangkau
        if nc -zv $TAILSCALE_IP 3389; then
          echo "TCP connectivity successful!"
        else
          echo "TCP connection to RDP port 3389 failed"
          exit 1
        fi

    - name: Maintain Connection
      run: |
        echo "=== RDP ACCESS ==="
        echo "Address: $TAILSCALE_IP"
        echo "Username: AiraaCheisyaa"
        echo "Password: ${{ env.RDP_PASSWORD }}"
        echo "=================="
        # Jaga agar runner tetap aktif
        sleep infinity
